-- AlterTable
ALTER TABLE `User` ADD COLUMN `activityLevel` ENUM('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE') NULL,
    ADD COLUMN `age` INTEGER NULL,
    ADD COLUMN `goalRateKgPerWeek` DOUBLE NULL,
    ADD COLUMN `heightCm` DOUBLE NULL,
    ADD COLUMN `nutritionGoal` ENUM('LOSE', 'MAINTAIN', 'GAIN') NOT NULL DEFAULT 'MAINTAIN',
    ADD COLUMN `sex` ENUM('MALE', 'FEMALE') NULL,
    ADD COLUMN `weightKg` DOUBLE NULL;
